# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_brand'),
        ('brands', '0002_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
