# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brand_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
