# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_brand_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='parent',
        ),
    ]
