# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_brand_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='products',
        ),
    ]
