# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170329_1227'),
        ('categories', '0006_auto_20170329_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.SubCategory1')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.SubCategory2')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
