# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170329_1227'),
        ('categories', '0007_subcategory2_subcategory3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory1',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategory2',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategory3',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategory3',
            name='products',
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
        migrations.DeleteModel(
            name='SubCategory1',
        ),
        migrations.DeleteModel(
            name='SubCategory2',
        ),
        migrations.DeleteModel(
            name='SubCategory3',
        ),
    ]
