# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproducts',
            name='brand',
            field=models.CharField(max_length=100, null=True, verbose_name=products.models.Product),
        ),
        migrations.AddField(
            model_name='newproducts',
            name='description',
            field=models.TextField(null=True, verbose_name=products.models.Product),
        ),
        migrations.AddField(
            model_name='newproducts',
            name='image',
            field=models.ImageField(null=True, upload_to=b'', verbose_name=products.models.Product),
        ),
        migrations.AddField(
            model_name='newproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name=products.models.Product),
        ),
    ]
