# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_status_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproducts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='status',
        ),
        migrations.DeleteModel(
            name='NewProducts',
        ),
    ]
