# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170420_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name=products.models.Product)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name=products.models.Product)),
                ('image', models.ImageField(null=True, upload_to=b'', verbose_name=products.models.Product)),
                ('brand', models.CharField(max_length=100, null=True, verbose_name=products.models.Product)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Status')),
            ],
        ),
    ]
