# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20170426_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='x',
            new_name='status',
        ),
    ]
