# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20170426_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Status'),
        ),
    ]
