# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_remove_brand_products'),
        ('products', '0020_auto_20170502_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brandname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand'),
        ),
    ]
